import type { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  // app.chatbotistic.com is the operational dashboard host. The public
  // marketing sitemap is generated by the canonical WordPress site.
  return []
}
