import type { MetadataRoute } from 'next'
import { widgets } from '@/lib/tochat/client'
import { publicReadScope } from '@/lib/tochat/org-config'

// app.chatbotistic.com is the operational dashboard host; the public
// marketing sitemap is generated by the canonical WordPress site. The
// only indexable app URLs are published chat landing pages — active
// widgets resolvable through the deployment's master account. The
// lookup is cached for an hour so crawlers can't hammer the provider.

export const dynamic = 'force-dynamic'

let cached: { at: number; entries: MetadataRoute.Sitemap } | null = null
const CACHE_TTL_MS = 60 * 60 * 1000

function siteOrigin(): string {
  return (process.env.NEXT_PUBLIC_SITE_URL || 'https://app.chatbotistic.com').replace(/\/$/, '')
}

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  if (cached && Date.now() - cached.at < CACHE_TTL_MS) {
    return cached.entries
  }

  const scope = publicReadScope()
  let entries: MetadataRoute.Sitemap = []
  if (scope) {
    try {
      const list = await widgets.list(scope)
      entries = list
        .filter((widget) => widget.active !== false && widget.id != null)
        .map((widget) => ({
          url: `${siteOrigin()}/whatsapp-business-directory/${encodeURIComponent(String(widget.id))}`,
        }))
    } catch (err) {
      // Provider unavailable — serve the cached/empty set rather than
      // a 500; search engines retry sitemaps regularly.
      console.error('[sitemap] landing lookup failed:', err instanceof Error ? err.message : err)
      entries = cached?.entries ?? []
    }
  }

  cached = { at: Date.now(), entries }
  return entries
}
